--------------------------------------------------------
--  File created - Wednesday-June-30-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADSL_EXCEL_TELEKOM_DETAIL
--------------------------------------------------------

  CREATE TABLE "SUNFLOWER"."ADSL_EXCEL_TELEKOM_DETAIL" 
   (	"ID" NUMBER(*,0), 
	"ADSL_EXCEL_TELEKOM_MASTER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ADSL_EXCEL_TEMPLATE_DETAIL_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"VALUE" VARCHAR2(300) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE, 
	 CONSTRAINT "AETD1_TO_AETD" FOREIGN KEY ("ADSL_EXCEL_TEMPLATE_DETAIL_ID")
	  REFERENCES "SUNFLOWER"."ADSL_EXCEL_TEMPLATE_DETAIL" ("ID") ENABLE, 
	 CONSTRAINT "AETD1_TO_AETM" FOREIGN KEY ("ADSL_EXCEL_TELEKOM_MASTER_ID")
	  REFERENCES "SUNFLOWER"."ADSL_EXCEL_TELEKOM_MASTER" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Table ADSL_EXCEL_TEMPLATE_DETAIL
--------------------------------------------------------

  CREATE TABLE "SUNFLOWER"."ADSL_EXCEL_TEMPLATE_DETAIL" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"HEADER" VARCHAR2(50) NOT NULL ENABLE, 
	"EXPRESSION" VARCHAR2(100), 
	"ALIGNMENT" VARCHAR2(20), 
	"REQUIRED" NUMBER(*,0) NOT NULL ENABLE, 
	"ADSL_EXCEL_TEMPLATE_MASTER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE, 
	 CONSTRAINT "AETD_TO_AETM" FOREIGN KEY ("ADSL_EXCEL_TEMPLATE_MASTER_ID")
	  REFERENCES "SUNFLOWER"."ADSL_EXCEL_TEMPLATE_MASTER" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Table ADSL_EXCEL_TRANSITION
--------------------------------------------------------

  CREATE TABLE "SUNFLOWER"."ADSL_EXCEL_TRANSITION" 
   (	"ID" NUMBER(*,0), 
	"ADSL_EXCEL_CASE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"TASK_PATTERN_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"STATE_IN_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"STATE_OUT_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"GROUP_NAME" VARCHAR2(70), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE, 
	 CONSTRAINT "AET_TO_SOUT" FOREIGN KEY ("STATE_OUT_ID")
	  REFERENCES "SUNFLOWER"."STATE" ("ID") ENABLE, 
	 CONSTRAINT "AET_TO_SIN" FOREIGN KEY ("STATE_IN_ID")
	  REFERENCES "SUNFLOWER"."STATE" ("ID") ENABLE, 
	 CONSTRAINT "AET_TO_TP" FOREIGN KEY ("TASK_PATTERN_ID")
	  REFERENCES "SUNFLOWER"."TASK_PATTERN" ("ID") ENABLE, 
	 CONSTRAINT "AET_TO_AEC" FOREIGN KEY ("ADSL_EXCEL_CASE_ID")
	  REFERENCES "SUNFLOWER"."ADSL_EXCEL_CASE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Table ADSL_STATUS
--------------------------------------------------------

  CREATE TABLE "SUNFLOWER"."ADSL_STATUS" 
   (	"ID" NUMBER(*,0), 
	"ORDER_NO" NUMBER(*,0), 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(400), 
	"GROUP_ID" NUMBER(*,0), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE, 
	 UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Table ADSL_TELEKOM_CHANGE
--------------------------------------------------------

  CREATE TABLE "SUNFLOWER"."ADSL_TELEKOM_CHANGE" 
   (	"ID" NUMBER(*,0), 
	"AGREEMENT_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"MG" VARCHAR2(10), 
	"PHONE_NUMBER" VARCHAR2(40), 
	"OLD_TELEKOM_PACKAGE" VARCHAR2(5), 
	"NEW_TELEKOM_PACKAGE" VARCHAR2(5), 
	"OPERATOR_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"INSERTION_DATE" DATE NOT NULL ENABLE, 
	"STATUS" NUMBER(*,0) NOT NULL ENABLE, 
	"ACTIVE" NUMBER(*,0) NOT NULL ENABLE, 
	"NOTE" VARCHAR2(200), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE, 
	 CONSTRAINT "FK_ATELC_TO_OPERATOR" FOREIGN KEY ("OPERATOR_ID")
	  REFERENCES "SUNFLOWER"."OPERATOR" ("ID") ENABLE, 
	 CONSTRAINT "FK_ATELC_TO_AGREEMENT" FOREIGN KEY ("AGREEMENT_ID")
	  REFERENCES "SUNFLOWER"."AGREEMENT" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Table AGREEMENT_DIARY
--------------------------------------------------------

  CREATE TABLE "SUNFLOWER"."AGREEMENT_DIARY" 
   (	"ID" NUMBER(*,0), 
	"AGREEMENT_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20), 
	"OPERATOR_ID" NUMBER(*,0), 
	"DIARY_DATE" DATE NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(200), 
	"ACTIVE" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "SYS_C008159" CHECK (STATUS in ('CREATED', 'STARTED', 'STOPPED', 'CANCELLED', 'SIGNED')) ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE, 
	 CONSTRAINT "FK_AD_TO_OP" FOREIGN KEY ("OPERATOR_ID")
	  REFERENCES "SUNFLOWER"."OPERATOR" ("ID") ENABLE, 
	 CONSTRAINT "FK_AD_TO_AGR" FOREIGN KEY ("AGREEMENT_ID")
	  REFERENCES "SUNFLOWER"."AGREEMENT" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "SUNFLOWER"."CLIENT" 
   (	"ID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(150), 
	"PASSWORD" VARCHAR2(40), 
	"PIN" VARCHAR2(50), 
	"ACTIVE" NUMBER(*,0), 
	"VALID" NUMBER(*,0), 
	"ACTIVE_AGREEMENTS" NUMBER(*,0), 
	"LAST_LOGIN" DATE, 
	"TOKEN_WITH_TIMESTAMPS" VARCHAR2(100), 
	 CONSTRAINT "CLIENT_UK1" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE, 
	 UNIQUE ("PIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Table OPERATOR
--------------------------------------------------------

  CREATE TABLE "SUNFLOWER"."OPERATOR" 
   (	"ID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(40) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(40) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(40), 
	"LAST_NAME" VARCHAR2(40), 
	"DISTRIBUTER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ACTIVE" NUMBER(*,0), 
	"RSS_FEED_ID" NUMBER(*,0), 
	"PORTA_USERNAME" VARCHAR2(40), 
	"PORTA_PASSWORD" VARCHAR2(40), 
	"PORTA_USER_ID" NUMBER, 
	"POS_ID" NUMBER(*,0), 
	"DEPARTMENT_CODE" VARCHAR2(15), 
	 UNIQUE ("PORTA_USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE, 
	 UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE, 
	 CONSTRAINT "FK_OP_TO_DIS" FOREIGN KEY ("DISTRIBUTER_ID")
	  REFERENCES "SUNFLOWER"."DISTRIBUTER" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Table PACKAGE_PRICE_LIST
--------------------------------------------------------

  CREATE TABLE "SUNFLOWER"."PACKAGE_PRICE_LIST" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(120) NOT NULL ENABLE, 
	"OPERATOR_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"SERVICE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"START_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE, 
	"INSERTION_DATE" DATE NOT NULL ENABLE, 
	"CLIENT_TYPE" VARCHAR2(30) NOT NULL ENABLE, 
	"PENALTY_TYPE_ID" NUMBER(*,0), 
	"AGREEMENT_OBLIGATION_ID" NUMBER(*,0), 
	"PENALTY_COEFFICIENT" NUMBER(9,2), 
	"USER_FORM_ID" NUMBER(*,0), 
	"EQUIPMENT_PRICE_LIST_ID" NUMBER(*,0), 
	"DEFAULT_LIST" NUMBER(1,0), 
	"DEFAULT_PERIOD" VARCHAR2(1), 
	"PAYMENT_DISCOUNT_ID" NUMBER(*,0), 
	"OBLIGATION_PERIOD" NUMBER, 
	"CLIENT_TARGET_GROUP" VARCHAR2(20), 
	"ADDITIONAL_SERVICE_PL_ID" NUMBER(*,0), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE, 
	 CONSTRAINT "PACKAGE_PRICE_LIST_TO_PD" FOREIGN KEY ("PAYMENT_DISCOUNT_ID")
	  REFERENCES "SUNFLOWER"."PAYMENT_DISCOUNT" ("ID") ENABLE, 
	 CONSTRAINT "PACKAGE_PRICE_LIST_TO_EPL" FOREIGN KEY ("EQUIPMENT_PRICE_LIST_ID")
	  REFERENCES "SUNFLOWER"."EQUIPMENT_PRICE_LIST" ("ID") ENABLE, 
	 CONSTRAINT "PACKAGE_PRICE_LIST_TO_UF" FOREIGN KEY ("USER_FORM_ID")
	  REFERENCES "SUNFLOWER"."USER_FORM" ("ID") ENABLE, 
	 CONSTRAINT "PACKAGE_PRICE_LIST_TO_AOI" FOREIGN KEY ("AGREEMENT_OBLIGATION_ID")
	  REFERENCES "SUNFLOWER"."AGREEMENT_OBLIGATION" ("ID") ENABLE, 
	 CONSTRAINT "PACKAGE_PRICE_LIST_TO_PENTY" FOREIGN KEY ("PENALTY_TYPE_ID")
	  REFERENCES "SUNFLOWER"."PENALTY_TYPE" ("ID") ENABLE, 
	 CONSTRAINT "PACKAGE_PRICE_LIST_TO_SER" FOREIGN KEY ("SERVICE_ID")
	  REFERENCES "SUNFLOWER"."SERVICE" ("ID") ENABLE, 
	 CONSTRAINT "PACKAGE_PRICE_LIST_TO_OP" FOREIGN KEY ("OPERATOR_ID")
	  REFERENCES "SUNFLOWER"."OPERATOR" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Table TASK_PATTERN
--------------------------------------------------------

  CREATE TABLE "SUNFLOWER"."TASK_PATTERN" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(40) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(200), 
	"ESTIMATED_TIME" VARCHAR2(10), 
	"TASK_PATTERN_SET_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"AUTOMATED_TASK_ID" NUMBER(*,0), 
	"DEPARTMENT_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ORDER_NO" NUMBER(*,0) NOT NULL ENABLE, 
	"SMS_TEMPLATE_ID" NUMBER, 
	"MAIL_TEMPLATE_ID" NUMBER, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE, 
	 CONSTRAINT "FK_TP_TO_AUTO_T" FOREIGN KEY ("AUTOMATED_TASK_ID")
	  REFERENCES "SUNFLOWER"."AUTOMATED_TASK" ("ID") ENABLE, 
	 CONSTRAINT "FK_TP_TO_DEP" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "SUNFLOWER"."DEPARTMENT" ("ID") ENABLE, 
	 CONSTRAINT "FK_TP_TO_TASKPS" FOREIGN KEY ("TASK_PATTERN_SET_ID")
	  REFERENCES "SUNFLOWER"."TASK_PATTERN_SET" ("ID") ENABLE, 
	 CONSTRAINT "FK_TP_TO_SMS" FOREIGN KEY ("SMS_TEMPLATE_ID")
	  REFERENCES "SUNFLOWER"."SMS_TEMPLATE" ("ID") ENABLE, 
	 CONSTRAINT "FK_TP_TO_MAIL" FOREIGN KEY ("MAIL_TEMPLATE_ID")
	  REFERENCES "SUNFLOWER"."MAIL_TEMPLATE" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Index SYS_C00124833
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUNFLOWER"."SYS_C00124833" ON "SUNFLOWER"."ADSL_EXCEL_CASE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Index SYS_C00124839
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUNFLOWER"."SYS_C00124839" ON "SUNFLOWER"."ADSL_EXCEL_TELEKOM_MASTER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Index SYS_C00124831
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUNFLOWER"."SYS_C00124831" ON "SUNFLOWER"."ADSL_EXCEL_TEMPLATE_MASTER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Index SYS_C00124858
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUNFLOWER"."SYS_C00124858" ON "SUNFLOWER"."ADSL_STATUS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Index SYS_C00124860
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUNFLOWER"."SYS_C00124860" ON "SUNFLOWER"."ADSL_STATUS_TASK_TRANSLATOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Index IND_PACK_AGR
--------------------------------------------------------

  CREATE INDEX "SUNFLOWER"."IND_PACK_AGR" ON "SUNFLOWER"."AGREEMENT" ("PACKAGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Index SYS_C00124734
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUNFLOWER"."SYS_C00124734" ON "SUNFLOWER"."AGREEMENT_DIARY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Index SYS_C00125017
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUNFLOWER"."SYS_C00125017" ON "SUNFLOWER"."APPLICATION_CONTACT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Index SYS_C00124679
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUNFLOWER"."SYS_C00124679" ON "SUNFLOWER"."CLIENT" ("PIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Index SYS_C00124876
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUNFLOWER"."SYS_C00124876" ON "SUNFLOWER"."HR_EMPLOYEE" ("ID_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Index IND_HRE_OP
--------------------------------------------------------

  CREATE INDEX "SUNFLOWER"."IND_HRE_OP" ON "SUNFLOWER"."HR_EMPLOYEE" ("OPERATOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Index SYS_C00124710
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUNFLOWER"."SYS_C00124710" ON "SUNFLOWER"."OPERATOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Index IND_SER_PACK
--------------------------------------------------------

  CREATE INDEX "SUNFLOWER"."IND_SER_PACK" ON "SUNFLOWER"."PACKAGE" ("SERVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Index SYS_C00124719
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUNFLOWER"."SYS_C00124719" ON "SUNFLOWER"."PACKAGE" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Index SYS_C00125021
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUNFLOWER"."SYS_C00125021" ON "SUNFLOWER"."PACKAGE_PRICE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Index SYS_C00124713
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUNFLOWER"."SYS_C00124713" ON "SUNFLOWER"."TASK_PATTERN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  DDL for Index SYS_C00124725
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUNFLOWER"."SYS_C00124725" ON "SUNFLOWER"."TASK_DIARY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"
--------------------------------------------------------
--  Constraints for Table ADSL_EXCEL_TELEKOM_DETAIL
--------------------------------------------------------

  ALTER TABLE "SUNFLOWER"."ADSL_EXCEL_TELEKOM_DETAIL" MODIFY ("ADSL_EXCEL_TELEKOM_MASTER_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."ADSL_EXCEL_TELEKOM_DETAIL" MODIFY ("ADSL_EXCEL_TEMPLATE_DETAIL_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."ADSL_EXCEL_TELEKOM_DETAIL" MODIFY ("VALUE" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."ADSL_EXCEL_TELEKOM_DETAIL" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE
--------------------------------------------------------
--  Constraints for Table ADSL_EXCEL_TEMPLATE_DETAIL
--------------------------------------------------------

  ALTER TABLE "SUNFLOWER"."ADSL_EXCEL_TEMPLATE_DETAIL" MODIFY ("NAME" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."ADSL_EXCEL_TEMPLATE_DETAIL" MODIFY ("HEADER" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."ADSL_EXCEL_TEMPLATE_DETAIL" MODIFY ("REQUIRED" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."ADSL_EXCEL_TEMPLATE_DETAIL" MODIFY ("ADSL_EXCEL_TEMPLATE_MASTER_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."ADSL_EXCEL_TEMPLATE_DETAIL" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE
--------------------------------------------------------
--  Constraints for Table ADSL_EXCEL_TRANSITION
--------------------------------------------------------

  ALTER TABLE "SUNFLOWER"."ADSL_EXCEL_TRANSITION" MODIFY ("ADSL_EXCEL_CASE_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."ADSL_EXCEL_TRANSITION" MODIFY ("TASK_PATTERN_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."ADSL_EXCEL_TRANSITION" MODIFY ("STATE_IN_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."ADSL_EXCEL_TRANSITION" MODIFY ("STATE_OUT_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."ADSL_EXCEL_TRANSITION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE
--------------------------------------------------------
--  Constraints for Table ADSL_STATUS_TASK_TRANSLATOR
--------------------------------------------------------

  ALTER TABLE "SUNFLOWER"."ADSL_STATUS_TASK_TRANSLATOR" MODIFY ("ADSL_STATUS_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."ADSL_STATUS_TASK_TRANSLATOR" MODIFY ("TASK_PATTERN_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."ADSL_STATUS_TASK_TRANSLATOR" MODIFY ("TASK_STATE_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."ADSL_STATUS_TASK_TRANSLATOR" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE
--------------------------------------------------------
--  Constraints for Table AGREEMENT
--------------------------------------------------------

  ALTER TABLE "SUNFLOWER"."AGREEMENT" MODIFY ("CLIENT_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."AGREEMENT" MODIFY ("OPERATOR_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."AGREEMENT" MODIFY ("PACKAGE_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."AGREEMENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE
--------------------------------------------------------
--  Constraints for Table APPLICATION_CONTACT
--------------------------------------------------------

  ALTER TABLE "SUNFLOWER"."APPLICATION_CONTACT" MODIFY ("CLIENT_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."APPLICATION_CONTACT" MODIFY ("PACKAGE_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."APPLICATION_CONTACT" MODIFY ("OPERATOR_APPLY_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."APPLICATION_CONTACT" MODIFY ("DATE_APPLY" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."APPLICATION_CONTACT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE
--------------------------------------------------------
--  Constraints for Table HR_EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "SUNFLOWER"."HR_EMPLOYEE" MODIFY ("OPERATOR_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."HR_EMPLOYEE" ADD UNIQUE ("ID_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE
 
  ALTER TABLE "SUNFLOWER"."HR_EMPLOYEE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE
--------------------------------------------------------
--  Constraints for Table PACKAGE
--------------------------------------------------------

  ALTER TABLE "SUNFLOWER"."PACKAGE" MODIFY ("NAME" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."PACKAGE" ADD CHECK (type in ('Pojedinac', 'Firma', 'Firma, Pojedinac')) ENABLE
 
  ALTER TABLE "SUNFLOWER"."PACKAGE" ADD CHECK (
PAYMENT_MODE in ('PREPAYED', 'POSTPAYED', 'PREPAID', 'POSTPAID')
) ENABLE
 
  ALTER TABLE "SUNFLOWER"."PACKAGE" ADD CHECK (CONTINUATION in ('CONTINUOUS', 'DISCONTINUOUS')) ENABLE
 
  ALTER TABLE "SUNFLOWER"."PACKAGE" ADD CHECK (LIMITED in ('DURATION', 'QUANTITY', 'DURATION/QUANTITY')) ENABLE
 
  ALTER TABLE "SUNFLOWER"."PACKAGE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE
 
  ALTER TABLE "SUNFLOWER"."PACKAGE" ADD UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE
--------------------------------------------------------
--  Constraints for Table PACKAGE_PRICE
--------------------------------------------------------

  ALTER TABLE "SUNFLOWER"."PACKAGE_PRICE" MODIFY ("PACKAGE_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."PACKAGE_PRICE" MODIFY ("PACKAGE_PRICE_LIST_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."PACKAGE_PRICE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE
--------------------------------------------------------
--  Constraints for Table TASK_DIARY
--------------------------------------------------------

  ALTER TABLE "SUNFLOWER"."TASK_DIARY" MODIFY ("TASK_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."TASK_DIARY" MODIFY ("STATE_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."TASK_DIARY" MODIFY ("PRIORITY_ID" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."TASK_DIARY" MODIFY ("DIARY_DATE" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."TASK_DIARY" MODIFY ("ACTIVE" NOT NULL ENABLE)
 
  ALTER TABLE "SUNFLOWER"."TASK_DIARY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SUNFLOWER"  ENABLE
--------------------------------------------------------
--  Ref Constraints for Table ADSL_EXCEL_TELEKOM_DETAIL
--------------------------------------------------------

  ALTER TABLE "SUNFLOWER"."ADSL_EXCEL_TELEKOM_DETAIL" ADD CONSTRAINT "AETD1_TO_AETD" FOREIGN KEY ("ADSL_EXCEL_TEMPLATE_DETAIL_ID")
	  REFERENCES "SUNFLOWER"."ADSL_EXCEL_TEMPLATE_DETAIL" ("ID") ENABLE
 
  ALTER TABLE "SUNFLOWER"."ADSL_EXCEL_TELEKOM_DETAIL" ADD CONSTRAINT "AETD1_TO_AETM" FOREIGN KEY ("ADSL_EXCEL_TELEKOM_MASTER_ID")
	  REFERENCES "SUNFLOWER"."ADSL_EXCEL_TELEKOM_MASTER" ("ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table ADSL_EXCEL_TEMPLATE_DETAIL
--------------------------------------------------------

  ALTER TABLE "SUNFLOWER"."ADSL_EXCEL_TEMPLATE_DETAIL" ADD CONSTRAINT "AETD_TO_AETM" FOREIGN KEY ("ADSL_EXCEL_TEMPLATE_MASTER_ID")
	  REFERENCES "SUNFLOWER"."ADSL_EXCEL_TEMPLATE_MASTER" ("ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table ADSL_STATUS_TASK_TRANSLATOR
--------------------------------------------------------

  ALTER TABLE "SUNFLOWER"."ADSL_STATUS_TASK_TRANSLATOR" ADD CONSTRAINT "FK_ASTT_TO_AS" FOREIGN KEY ("ADSL_STATUS_ID")
	  REFERENCES "SUNFLOWER"."ADSL_STATUS" ("ID") ENABLE
 
  ALTER TABLE "SUNFLOWER"."ADSL_STATUS_TASK_TRANSLATOR" ADD CONSTRAINT "FK_ASTT_TO_TP" FOREIGN KEY ("TASK_PATTERN_ID")
	  REFERENCES "SUNFLOWER"."TASK_PATTERN" ("ID") ENABLE
 
  ALTER TABLE "SUNFLOWER"."ADSL_STATUS_TASK_TRANSLATOR" ADD CONSTRAINT "FK_ASTT_TO_TS" FOREIGN KEY ("TASK_STATE_ID")
	  REFERENCES "SUNFLOWER"."STATE" ("ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table AGREEMENT
--------------------------------------------------------

  ALTER TABLE "SUNFLOWER"."AGREEMENT" ADD CONSTRAINT "FK_AGREEMENT_TO_PARENT_AGR" FOREIGN KEY ("PARENT_AGREEMENT_ID")
	  REFERENCES "SUNFLOWER"."AGREEMENT" ("ID") ENABLE
 
  ALTER TABLE "SUNFLOWER"."AGREEMENT" ADD CONSTRAINT "FK_AGR_TO_CLIENT" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "SUNFLOWER"."CLIENT" ("ID") ENABLE
 
  ALTER TABLE "SUNFLOWER"."AGREEMENT" ADD CONSTRAINT "FK_AGR_TO_CONTACT" FOREIGN KEY ("CONTACT_ID")
	  REFERENCES "SUNFLOWER"."CONTACT" ("ID") ENABLE
 
  ALTER TABLE "SUNFLOWER"."AGREEMENT" ADD CONSTRAINT "FK_AGR_TO_PACKAGE" FOREIGN KEY ("PACKAGE_ID")
	  REFERENCES "SUNFLOWER"."PACKAGE" ("ID") ENABLE
 
  ALTER TABLE "SUNFLOWER"."AGREEMENT" ADD CONSTRAINT "FK_QGR_TO_OPERATOR" FOREIGN KEY ("OPERATOR_ID")
	  REFERENCES "SUNFLOWER"."OPERATOR" ("ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table APPLICATION_CONTACT
--------------------------------------------------------

  ALTER TABLE "SUNFLOWER"."APPLICATION_CONTACT" ADD CONSTRAINT "FK_APPLC_CONTACT_TO_AGR" FOREIGN KEY ("AGREEMENT_ID")
	  REFERENCES "SUNFLOWER"."AGREEMENT" ("ID") ENABLE
 
  ALTER TABLE "SUNFLOWER"."APPLICATION_CONTACT" ADD CONSTRAINT "FK_APPLC_CONTACT_TO_PAC" FOREIGN KEY ("PACKAGE_ID")
	  REFERENCES "SUNFLOWER"."PACKAGE" ("ID") ENABLE
 
  ALTER TABLE "SUNFLOWER"."APPLICATION_CONTACT" ADD CONSTRAINT "FK_APPLC_CONTACT_TO_PROM" FOREIGN KEY ("PROMOTION_ID")
	  REFERENCES "SUNFLOWER"."PROMOTION" ("ID") ENABLE
 
  ALTER TABLE "SUNFLOWER"."APPLICATION_CONTACT" ADD CONSTRAINT "FK_APPLC_CONTACT_TO_R_OPER" FOREIGN KEY ("OPERATOR_RESOLVE_ID")
	  REFERENCES "SUNFLOWER"."OPERATOR" ("ID") ENABLE
 
  ALTER TABLE "SUNFLOWER"."APPLICATION_CONTACT" ADD CONSTRAINT "FK_APPLC_CONTACT_TO_R_PPL" FOREIGN KEY ("PACKAGE_PRICE_LIST_ID")
	  REFERENCES "SUNFLOWER"."PACKAGE_PRICE_LIST" ("ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table OPERATOR
--------------------------------------------------------

  ALTER TABLE "SUNFLOWER"."OPERATOR" ADD CONSTRAINT "FK_OP_TO_DIS" FOREIGN KEY ("DISTRIBUTER_ID")
	  REFERENCES "SUNFLOWER"."DISTRIBUTER" ("ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table PACKAGE_PRICE_LIST
--------------------------------------------------------

  ALTER TABLE "SUNFLOWER"."PACKAGE_PRICE_LIST" ADD CONSTRAINT "PACKAGE_PRICE_LIST_TO_AOI" FOREIGN KEY ("AGREEMENT_OBLIGATION_ID")
	  REFERENCES "SUNFLOWER"."AGREEMENT_OBLIGATION" ("ID") ENABLE
 
  ALTER TABLE "SUNFLOWER"."PACKAGE_PRICE_LIST" ADD CONSTRAINT "PACKAGE_PRICE_LIST_TO_EPL" FOREIGN KEY ("EQUIPMENT_PRICE_LIST_ID")
	  REFERENCES "SUNFLOWER"."EQUIPMENT_PRICE_LIST" ("ID") ENABLE
 
  ALTER TABLE "SUNFLOWER"."PACKAGE_PRICE_LIST" ADD CONSTRAINT "PACKAGE_PRICE_LIST_TO_OP" FOREIGN KEY ("OPERATOR_ID")
	  REFERENCES "SUNFLOWER"."OPERATOR" ("ID") ENABLE
 
  ALTER TABLE "SUNFLOWER"."PACKAGE_PRICE_LIST" ADD CONSTRAINT "PACKAGE_PRICE_LIST_TO_PD" FOREIGN KEY ("PAYMENT_DISCOUNT_ID")
	  REFERENCES "SUNFLOWER"."PAYMENT_DISCOUNT" ("ID") ENABLE
 
  ALTER TABLE "SUNFLOWER"."PACKAGE_PRICE_LIST" ADD CONSTRAINT "PACKAGE_PRICE_LIST_TO_PENTY" FOREIGN KEY ("PENALTY_TYPE_ID")
	  REFERENCES "SUNFLOWER"."PENALTY_TYPE" ("ID") ENABLE
 
  ALTER TABLE "SUNFLOWER"."PACKAGE_PRICE_LIST" ADD CONSTRAINT "PACKAGE_PRICE_LIST_TO_SER" FOREIGN KEY ("SERVICE_ID")
	  REFERENCES "SUNFLOWER"."SERVICE" ("ID") ENABLE
 
  ALTER TABLE "SUNFLOWER"."PACKAGE_PRICE_LIST" ADD CONSTRAINT "PACKAGE_PRICE_LIST_TO_UF" FOREIGN KEY ("USER_FORM_ID")
	  REFERENCES "SUNFLOWER"."USER_FORM" ("ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table TASK_DIARY
--------------------------------------------------------

  ALTER TABLE "SUNFLOWER"."TASK_DIARY" ADD CONSTRAINT "FK_TD_TO_OP_ASS" FOREIGN KEY ("OPERATOR_ASSIGNED_ID")
	  REFERENCES "SUNFLOWER"."OPERATOR" ("ID") ENABLE
 
  ALTER TABLE "SUNFLOWER"."TASK_DIARY" ADD CONSTRAINT "FK_TD_TO_OP_UPD" FOREIGN KEY ("OPERATOR_UPDATED_ID")
	  REFERENCES "SUNFLOWER"."OPERATOR" ("ID") ENABLE
 
  ALTER TABLE "SUNFLOWER"."TASK_DIARY" ADD CONSTRAINT "FK_TD_TO_PRIOR" FOREIGN KEY ("PRIORITY_ID")
	  REFERENCES "SUNFLOWER"."PRIORITY" ("ID") ENABLE
 
  ALTER TABLE "SUNFLOWER"."TASK_DIARY" ADD CONSTRAINT "FK_TD_TO_STATE" FOREIGN KEY ("STATE_ID")
	  REFERENCES "SUNFLOWER"."STATE" ("ID") ENABLE
 
  ALTER TABLE "SUNFLOWER"."TASK_DIARY" ADD CONSTRAINT "FK_TD_TO_TASK" FOREIGN KEY ("TASK_ID")
	  REFERENCES "SUNFLOWER"."TASK" ("ID") ENABLE
